### ISSUE TITLE
Use consistent parameter naming

### ISSUE THREAD

**Issue by lukasvan3l** [xavcz/papa-clicker#1]
https://github.com/xavcz/papa-clicker/blob/master/client/templates/center/stats.js#L13

Renaming these parameters only makes it confusing, better to pass the original documents. Also this helps if at some point you want to add more information.

``` js
bonuses: function() {
  let belongings = Belongings.find({userId: Meteor.userId()});
  return belongings.map(function(belonging) {
    let bonus = Bonus.findOne({_id: belonging.belongingId});
    return !bonus ? null : {
      bonus: bonus,
      belonging: belonging,
      bonusPerSec: belonging.amount * bonus.production
    }
  }).filter((r) => r != null);
}
```

**Comment by xavxyz** [comment]
:100: @lukasvan3l 
Confusion = bug. Avoid confusion
